# $ref: '#/definitions/State'

type: object
additionalProperties: false
properties:
  entities:
    type: object
    additionalProperties:
      $ref: '#/definitions/Entity'

definitions:


  Direction:
    type: string
    enum:
      - negative
      - neutral
      - positive


  Entity:
    type: object
    additionalProperties: false
    properties:
      # name: str
      quantities:
        type: object
        additionalProperties:
          $ref: '#/definitions/Quantity'
      relations:
        type: object
        additionalProperties:
          $ref: '#/definitions/Relationship'


  Quantity:
    # name:
    #   type: str
    # quantitySpace:
    #   type: EnumMeta
    # TODO: figure out how to factor above vs. below fields
    # qty: str
    # change: Direction
    type: array
    items:
      type: string


  Relationship:
    anyOf:
      - $ref: '#/definitions/Influence'
      - $ref: '#/definitions/Proportional'
      - $ref: '#/definitions/VC'

  BaseRelationship:
    type: object
    properties:
      type:
        type: string
      a:
        type: string  # Quantity
      b:
        type: string  # Quantity
        # ^ EnumMeta?


  Influence:
    allOf:
      - $ref: '#/definitions/BaseRelationship'
      - properties:
          type:
            type: string
            enum:
              - influence
          correlation:
            $ref: '#/definitions/Direction'


  Proportional:
    allOf:
      - $ref: '#/definitions/BaseRelationship'
      - properties:
          type:
            type: string
            enum:
              - proportional
          correlation:
            $ref: '#/definitions/Direction'


  # EqualityRelation:
  #   enum:
  #     - LTE
  #     - LT
  #     - EQ
  #     - GT
  #     - GTE


  # Inequality:
  #   allOf:
  #     - $ref: '#/definitions/BaseRelationship'
  #     - properties:
  #         equality:
  #           type: EqualityRelation
  #           default: EqualityRelation.EQ


  VC:
    type: object
    additionalProperties: false
    properties:
      type:
        type: string
        enum:
          - VC
      a:
        type: string  # Enum
      b:
        type: string  # Enum


  # Addition:
  #   allOf:
  #     - $ref: '#/definitions/BaseRelationship'
  #     - properties:
  #         c:
  #           type: Quantity


  # Subtraction:
  #   allOf:
  #     - $ref: '#/definitions/BaseRelationship'
  #     - properties:
  #         c:
  #           type: Quantity


  State:
    type: object
    additionalProperties: false
    properties:
      entities:
        type: object
        additionalProperties:
          $ref: '#/definitions/Entity'


  StateGraph:
    # TODO: ???
    states:
      type: array
      items:
        type: State
